# Generated by Django 3.0.5 on 2021-02-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_auto_20210220_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='is_published',
            field=models.BooleanField(default=0, verbose_name='Is Published'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='youtube_link',
            field=models.URLField(blank=True, verbose_name='Link'),
        ),
    ]
